-- SUPABASE SQL SCHEMA FOR ANVITHA PORTFOLIO
-- Execute this in the Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)

-- 1. Projects Table
CREATE TABLE IF NOT EXISTS projects (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT,
    category TEXT,
    description TEXT,
    image TEXT,
    tags JSONB DEFAULT '[]'::jsonb,
    link TEXT,
    media JSONB DEFAULT '[]'::jsonb,
    "sortOrder" INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Experiences Table
CREATE TABLE IF NOT EXISTS experiences (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    role TEXT,
    company TEXT,
    period TEXT,
    location TEXT,
    summary TEXT,
    tags JSONB DEFAULT '[]'::jsonb,
    wins JSONB DEFAULT '[]'::jsonb,
    "behindTheResume" TEXT,
    "showImage" BOOLEAN DEFAULT FALSE,
    image TEXT,
    "imageCaption" TEXT,
    "presentationLink" TEXT,
    "attachmentLink" TEXT,
    "attachmentText" TEXT,
    "sortOrder" INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Skills Table
CREATE TABLE IF NOT EXISTS skills (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT,
    type TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Content Table (Global Settings)
CREATE TABLE IF NOT EXISTS content (
    key TEXT PRIMARY KEY,
    value TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Education Table
CREATE TABLE IF NOT EXISTS education (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    school TEXT,
    degree TEXT,
    field TEXT,
    location TEXT,
    period TEXT,
    gpa TEXT,
    details TEXT,
    "sortOrder" INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Certifications Table
CREATE TABLE IF NOT EXISTS certifications (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT,
    issuer TEXT,
    date TEXT,
    link TEXT,
    "sortOrder" INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Optional: Enable Row Level Security (RLS)
-- By default, for a personal portfolio, you might want to allow public READ access.
-- RUN THESE IF YOU WANT PUBLIC DATA:

ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read-only access" ON projects FOR SELECT USING (true);

ALTER TABLE experiences ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read-only access" ON experiences FOR SELECT USING (true);

ALTER TABLE skills ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read-only access" ON skills FOR SELECT USING (true);

ALTER TABLE content ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read-only access" ON content FOR SELECT USING (true);

ALTER TABLE education ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read-only access" ON education FOR SELECT USING (true);

ALTER TABLE certifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read-only access" ON certifications FOR SELECT USING (true);
